### ISSUE TITLE
Set a Wi-Fi channel

### ISSUE THREAD

**Issue by shelland** [SkypLabs/probequest#15]
Hi, can you please explain a concept of channel switching? I suppose that Wi-Fi devices use several channels to broadcast their probe frames. How can I define a channel to collect such requests using your script?

**Comment by shelland** [comment]
After some investigation it seems like I need to change a channel using an **iw** command line utility.

**Comment by SkypLabs** [comment]
Hi @shelland,

Yes indeed, ProbeQuest doesn't have this option at the moment. If you want to set a specific channel number, you need to do it manually with an external tool. For example, `iw dev wlan0 set channel 11`.

This option will be implemented in ProbeQuest later on.
