### ISSUE TITLE
Arguments not working (-e, -r)

### ISSUE THREAD

**Issue by codingbart** [SkypLabs/probequest#17]
Dear author,

I cannot get the arguments to have any effect on the results.
For example, filtering on ESSID does not seem to work. 

![image](https://user-images.githubusercontent.com/36550063/53682010-bb611f00-3cf1-11e9-8ecc-4775f0b51630.png)

I also tried not using quotes. Tried --essid, -r, --regex, nothing seems to have any effect on the results I am seeing.

![image](https://user-images.githubusercontent.com/36550063/53682258-fb290600-3cf3-11e9-8812-4fbc3e3c2e8b.png)

Could you help me out with this? I must be doing something wrong here.

**Comment by SkypLabs** [comment]
Hi @codingbart,

There is nothing wrong with your command-line. It is apparently a bug I introduced with 5f2a3efe5ff94bfcbe4706c24794a73283a91877 while refactoring the way arguments are passed to the different components of the software. These arguments are not properly tested so I didn't realise my mistake.

I just issued a patch (v0.7.1) to address this bug and I will add tests not to let it happen again.

Thanks again for your valuable contribution!
