### ISSUE TITLE
Possible on Windows?

### ISSUE THREAD

**Issue by openedhardware** [SkypLabs/probequest#21]
Just wondering if this is capable with Windows10?

Cheers

**Comment by SkypLabs** [comment]
Hi @openedhardware,

I haven't had the occasion to test ProbeQuest on Windows since I don't use this OS at all. In theory, it should work given that ProbeQuest relies on Scapy which is multi-platform.

I will try to get my hands on a Windows machine to test it in practice.

**Comment by openedhardware** [comment]
@SkypLabs 
I got it working on Windows using Scapy.
Thanks!

**Comment by SkypLabs** [comment]
Great!

Thanks for your feedback.
