### ISSUE TITLE
Instant error while running

### ISSUE THREAD

**Issue by jmvermeulen** [SkypLabs/probequest#5]
Running _probquest -i wlan0_ instantly results in this error:

```
root@raspberrypi:/# probequest -i wlan0
[*] Start sniffing probe requests...
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.5/dist-packages/probequest/probe_request_sniffer.py", line 251, in run
    probe_request = self.parse(packet)
  File "/usr/local/lib/python3.5/dist-packages/probequest/probe_request_sniffer.py", line 285, in parse
    essid = packet.getlayer(Dot11ProbeReq).info.decode("utf-8")
AttributeError: 'NoneType' object has no attribute 'info'
```

The software is running on a Raspberry PI 3 with the most recent raspbian.

**Comment by jmvermeulen** [comment]
A raw packet example that causes this error:

`b"\x00\x00\x1a\x00/H\x00\x00eG\xafX\x01\x00\x00\x00\x10\x02\x94\t\xa0\x00\xbc\x01\x00\x00P\x00:\x01\xbc\xa8\xa6\xbf\xbba\x94\x10>\x901z\x94\x10>\x901z\x80\xb0\xc5\x88\xf8\xda\xc1\x00\x00\x00d\x001\x04\x00\tWeerbrand\x01\x08\x82\x84\x8b\x96\x0c\x12\x18$\x03\x01\x01*\x01\x002\x040H`l0\x14\x01\x00\x00\x0f\xac\x04\x01\x00\x00\x0f\xac\x04\x01\x00\x00\x0f\xac\x02\x00\x00-\x1ao\x00\x17\xff\xff\xff\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x1f\xff\x07\x18\x00=\x16\x01\x00\x06\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00J\x0e\x14\x00\n\x00\xb4\x00\xc8\x00\x14\x00\x05\x00\x19\x00\x7f\x08\x01\x00\x00\x00\x00\x00\x00\x00\xbf\x0c0y\x833\xea\xff\x00\x00\xea\xff\x00\x00\xc0\x05\x00\x00\x00\xc0\xff\xdd\x1e\x00\x90L3n\x00\x17\xff\xff\xff\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x1f\xff\x07\x18\x00\xdd\x1a\x00\x90L4\x01\x05\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xdd\x06\x00PC\x03\x00\x00\xdd\x18\x00P\xf2\x02\x01\x01\x80\x00\x03\xa4\x00\x00'\xa4\x00\x00BC^\x00b2/\x00\x7f\x06\x00\x00\x00\x02\x00@\xdd\x94\x00P\xf2\x04\x10J\x00\x01\x10\x10D\x00\x01\x02\x10;\x00\x01\x03\x10G\x00\x10\x7f\x12A7\xb9>\xc9\xf0\xdf\xce57\xf6+^\x80\x10!\x00\x0cLinksys, LLC\x10#\x00\tWRT1900AC\x10$\x00\tWRT1900AC\x10B\x00\x0e13J1060A417612\x10T\x00\x08\x00\x06\x00P\xf2\x04\x00\x01\x10\x11\x00\x0cLinksys17612\x10\x08\x00\x02 \x0c\x10<\x00\x01\x01\x10I\x00\x06\x007*\x00\x01 \xb1\x88/8"`

Al you can see there are multiple SSID's as plain text in the packet.

**Comment by SkypLabs** [comment]
Hi @jmvermeulen,

Thank you for reporting this issue and for the raw packet. I will have a look at it as soon as possible.

**Comment by jmvermeulen** [comment]
@SkypLabs thanks!
I found this code with the same goal, maybe the same if statement makes sense here?
https://github.com/0x90/iSniff/blob/1c24c08c0d8dedb75aa8274c05779f721add5729/iSniff.py#L33

If I can help you debug, please let me know :-)

**Comment by SkypLabs** [comment]
Oh thanks @jmvermeulen, I really appreciate!

I'm adding unit tests for the `ProbeRequestSniffer.ProbeRequestParser.parse()` method. Thank you for the link, it will be useful :+1:

By the way, would you be interested in participating in this project more often? I have a list of features I would like to implement for no much time for that.

**Comment by adamistheanswer** [comment]
Same issue although different line

File "/usr/lib/python3.5/threading.py", line 916, in _bootstrap_inner

**Comment by soupnatzi** [comment]
similar issue..

root@soup-natzi:~/probequest# probequest -i wlan1
[*] Start sniffing probe requests...
Traceback (most recent call last):
  File "/usr/local/bin/probequest", line 4, in <module>
    __import__('pkg_resources').run_script('probequest==0.6.1', 'probequest')
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 654, in run_script
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 1441, in run_script
  File "/usr/local/lib/python2.7/dist-packages/probequest-0.6.1-py2.7.egg/EGG-INFO/scripts/probequest", line 69, in <module>
  File "build/bdist.linux-x86_64/egg/probequest/ui/raw.py", line 31, in __init__
  File "build/bdist.linux-x86_64/egg/probequest/probe_request_sniffer.py", line 32, in __init__
  File "build/bdist.linux-x86_64/egg/probequest/probe_request_sniffer.py", line 97, in new_sniffer
  File "build/bdist.linux-x86_64/egg/probequest/probe_request_sniffer.py", line 129, in __init__
TypeError: super() takes at least 1 argument (0 given)

**Comment by SkypLabs** [comment]
@adamistheanswer @soupnatzi Could you give me more details about the version you use?

Typically @soupnatzi , I see in your traceback the file `probequest/ui/raw.py` which has been introduced with commit 62477018651935e99d770dc5b64576b59daa8cc9 which is 6 commits ahead of the last release. You should only use the latest release version and not what is under development (and consequently not considered as stable).

I will update the installation documentation to precise this point for those who want to install ProbeQuest from its source code.

**Comment by soupnatzi** [comment]
sure. i am running version 0.6.1

**Comment by soupnatzi** [comment]
so i restarted the usb adapter and it started working.

**Comment by SkypLabs** [comment]
> sure. i am running version 0.6.1.using alfa usb adapter awus036ach 802.11ac utra range

Actually, as said in my previous message, you are using a version which is in between `v0.6.1` and the future `v0.7.0` because `probequest/ui/raw.py` doesn't exist in `v0.6.1`. I suspect you have installed ProbeQuest from its source code and you didn't do a `git checkout v0.6.1` (I will specify this point in the documentation) to use the latest release version. Consequently, you are using an unfinished (and potentially buggy) version despite what `pip` and `probequest --version` tell you.

> so i restarted the usb adapter and it started working.

Glad to know that it works for you now.

**Comment by SkypLabs** [comment]
I just issued a patched version (`v0.6.2`) to address this issue. It's just a quick patch until I finish my work on `v0.7.0` which will contain rigorous unit tests.

**Comment by SkypLabs** [comment]
@jmvermeulen To analyse the raw frame you gave me, I used the code below producing this [PDF](https://github.com/SkypLabs/probequest/files/2456389/raw_frame_decoded.pdf).

```
from scapy.all import *

raw_frame = "x00\x00\x1a\x00/H\x00\x00eG¯X\x01\x00\x00\x00\x10\x02\x94\t\xa0\x00¼\x01\x00\x00P\x00:\x01¼¨¦¿»a\x94\x10>\x901z\x94\x10>\x901z\x80°Å\x88øÚÁ\x00\x00\x00d\x001\x04\x00\tWeerbrand\x01\x08\x82\x84\x8b\x96\x0c\x12\x18$\x03\x01\x01*\x01\x002\x040H`l0\x14\x01\x00\x00\x0f¬\x04\x01\x00\x00\x0f¬\x04\x01\x00\x00\x0f¬\x02\x00\x00-\x1ao\x00\x17ÿÿÿ\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x1fÿ\x07\x18\x00=\x16\x01\x00\x06\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00J\x0e\x14\x00\n\x00´\x00È\x00\x14\x00\x05\x00\x19\x00\x7f\x08\x01\x00\x00\x00\x00\x00\x00\x00¿\x0c0y\x833êÿ\x00\x00êÿ\x00\x00À\x05\x00\x00\x00ÀÿÝ\x1e\x00\x90L3n\x00\x17ÿÿÿ\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x1fÿ\x07\x18\x00Ý\x1a\x00\x90L4\x01\x05\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00Ý\x06\x00PC\x03\x00\x00Ý\x18\x00Pò\x02\x01\x01\x80\x00\x03¤\x00\x00'¤\x00\x00BC^\x00b2/\x00\x7f\x06\x00\x00\x00\x02\x00@Ý\x94\x00Pò\x04\x10J\x00\x01\x10\x10D\x00\x01\x02\x10;\x00\x01\x03\x10G\x00\x10\x7f\x12A7¹>ÉðßÎ57ö+^\x80\x10!\x00\x0cLinksys,LLC\x10#\x00\tWRT1900AC\x10$\x00\tWRT1900AC\x10B\x00\x0e13J1060A417612\x10T\x00\x08\x00\x06\x00Pò\x04\x00\x01\x10\x11\x00\x0cLinksys17612\x10\x08\x00\x02\x0c\x10<\x00\x01\x01\x10I\x00\x06\x007*\x00\x01±\x88/8"

frame_decoded = RadioTap(raw_frame)
frame_decoded.pdfdump("raw_frame_decoded.pdf")
```

As we can see in the PDF, the frame does not contain any `Dot11ProbeReq` layer, hence the if statement I added in `v0.6.2`.

**Comment by SkypLabs** [comment]
Unit tests have been added and I just released version 0.7.0.

Thank you all for your help.

**Comment by jmvermeulen** [comment]
Thanks! Will retry soon :-)

**Comment by maroun11970** [comment]
probequest -i wlan1mon
[*] Start sniffing probe requests.
won't sniff any pocket .any help would be appreciated.

**Comment by SkypLabs** [comment]
Hi @maroun11970,

To be able to help you, I need more information about your setup. What version of ProbeQuest do you use? How have you installed it? Have you enabled the monitor mode?...

Additionally, could you please open a new issue for your request? Your problem doesn't seem to be related to the one of the current thread.

Cheers.
